TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('dokter/', include('dokter.urls')),
    path('pasien/', include('pasien.urls')),
    path('ruanganhotel/', include('ruanganhotel.urls')),
    path('reservasihotel/', include('reservasihotel.urls')),
    path('transaksihotel/', include('transaksihotel.urls')),
    path('transaksibooking/', include('transaksibooking.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('faskes/', include('faskes.urls')),
]

dokter/urls.py
from django.urls import path, include
from . import views

app_name = 'dokter'
urlpatterns = [ 
	path('createAppointment/', views.createAppointment, name='createAppointment'),
    path('formAppointment/', views.formAppointment, name='formAppointment'),
    path('listAppointment/', views.listAppointment, name='listAppointment'),
    path('deleteAppointment/', views.deleteAppointment, name='deleteAppointment'),
    path('updateAppointment/', views.updateAppointment, name='updateAppointment'),
    path('ajaxAppointment/', views.ajaxAppointment, name='ajaxAppointment'),

    path('createJadwal/', views.createJadwal, name='createJadwal'),
    path('readJadwal/', views.readJadwal, name='readJadwal'),
    path('listJadwal/', views.listJadwal, name='listJadwal'),

	path('createRuanganRS/', views.createRuanganRS, name='createRuanganRS'),
    path('listRuanganRS/', views.listRuanganRS, name='listRuanganRS'),
    path('updateRuanganRS/', views.updateRuanganRS, name='updateRuanganRS'),
    path('ajaxKodeRS/', views.ajaxKodeRS, name='ajaxKodeRS'),
	path('ajaxRuanganRS/', views.ajaxRuanganRS, name='ajaxRuanganRS'),

    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('listBedRS/', views.listBedRS, name='listBedRS'),
    path('deleteBedRS/', views.deleteBedRS, name='deleteBedRS'),
    path('ajaxRuanganBed/', views.ajaxRuanganBed, name='ajaxRuanganBed'),
	path('ajaxKodeBed/', views.ajaxKodeBed, name='ajaxKodeBed'),

]

profilpengguna/urls.py
from django.urls import path
from . import views

app_name = "profilpengguna"

urlpatterns = [
    # path('', views.profil_view, name='profil'),
    path('profile-admin-sistem/', views.admin_view, name='profiladminsistem'),
    path('profile-pengguna-publik/', views.publik_view, name='profilpenggunapublik'),
    path('profile-dokter/', views.dokter_view, name='profildokter'),
    path('profile-admin-satgas/', views.satgas_view, name='profiladminsatgas'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.user_login, name='mylogin'),
    path('register/adminsistem/', views.admin_sistem_view, name='regadminsistem'),
    path('register/penggunapublik/', views.pengguna_publik_form_view, name='regpenggunappublik'),
    path('register/dokter/', views.dokter_form_view, name='regdokter'),
    path('register/adminsatgas/', views.admin_satgas_form_view, name='regadminsatgas'),
    path('logout/', views.userLogout, name='logout'),
]

dokter/models.py
from django.db import models

# Create your models here.

profilpengguna/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

dokter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sessions.models import Session
from django.db import connection, transaction, IntegrityError
from .forms import *
from django.core import serializers
from django.http import JsonResponse, HttpResponseRedirect
from homepage.views import user_login_required 
from django.urls import reverse
from users.views import getrole
from django.db import connection
import datetime

def dictfecthall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row)) 
        for row in cursor.fetchall()
        ]

#APPOINTMENT ------------------------------------------------------------------------------------------------------
def createAppointment(request):
    # print (getrole)
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]  
        print(username) 
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.JADWAL_DOKTER")
        data_appointment = dictfecthall(cursor)
    return render(request, 'create-appointment.html', {'appointment': data_appointment})

def formAppointment(request): 
    with connection.cursor() as cursor:
        print('sebelum set siruco')
        cursor.execute("SET search_path to SIRUCO;")
        print ('before tes dok')
        username = request.session["username"]
        
        if request.method == 'POST':
            # form = createAppointment(request.POST)
            # if form.is_valid():
            nik = request.POST.get('nik_pasien')
            email = request.POST.get('email')
            kode = request.POST.get('kode_faskes')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')
            rekomendasi = '...'
            print(nik)
            isi = {'email': email, 
                'kode_faskes': kode, 
                'tanggal': tanggal,
                'shift': shift}

            with connection.cursor() as cursor:
                cursor.execute("SELECT NoSTR FROM SIRUCO.DOKTER where username=%s LIMIT 1;", [email])
                no_str = cursor.fetchone()[0]
                print(no_str)
                
            if no_str is None:
                return redirect('dokter:formAppointment')
            print('tes dokter')
            try: 
                print('tes dokter 2')
            #Insert into MEMERIKSA 
                with connection.cursor() as cursor:
                    
                    print('tes dok')
                    cursor.execute("SET search_path TO SIRUCO;")
                    print(nik, no_str, email, kode, shift, tanggal, rekomendasi)
                    cursor.execute("INSERT INTO MEMERIKSA "
                                    "VALUES ('{}', '{}', '{}', '{}', '{}','{}', '{}');"
                                    .format(nik, no_str, email, kode, shift, tanggal, rekomendasi))
                    print('tes dokk')
                
                return redirect('dokter:listAppointment')

            except: 
                print('tes dokter 3')
                form=CreateAppointment(initial=isi)
                return render(request, 'form-appointment.html', 
                {'form': form, 'message': 'Tidak bisa membuat perjanjian dengan dokter, silahkan pilih jadwal lainnya.'})
        
        elif request.method == 'GET':
            print('tes dokter 4')
            username = request.GET.get('username')
            kode_faskes = request.GET.get('kode_faskes')
            shift = request.GET.get('shift')
            tanggal = request.GET.get('tanggal')
            print(username, kode_faskes, shift, tanggal)

            isi = {
                'email': username, 
                'kode_faskes': kode_faskes, 
                'tanggal': tanggal,
                'shift': shift} 

            print(isi)
            if username is None or kode_faskes is None or shift is None or tanggal is None:
                print("masuk none yg atas")
                return redirect('dokter:createAppointment')

            if isi is None:
                return redirect('dokter:createAppointment')

            form=CreateAppointment(initial=isi)
        return render(request, 'form-appointment.html', {'form': form})

def ajaxAppointment(request):
    print("MASUK AJAX")
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        pendaftar = request.session["username"]  
    print(pendaftar)
    if request.session.get("role") == "PENGGUNA_PUBLIK":
        with connection.cursor() as cursor:
            cursor.execute("SELECT NIK, NIK FROM SIRUCO.PASIEN where IdPendaftar = %s", [pendaftar])
            data = cursor.fetchall()
    else:
        print('masuk else ajax')
        with connection.cursor() as cursor:
            cursor.execute("SELECT NIK, NIK FROM SIRUCO.PASIEN")
            data = cursor.fetchall()
    nik_pasien = []
    for i in data:
        nik_pasien.append(i[0])
    print(nik_pasien)
    return JsonResponse({'id': nik_pasien})

def listAppointment(request) : 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]  
        print(username)

        if request.session.get('role') == 'ADMIN_SATGAS':
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM SIRUCO.MEMERIKSA;")
                data_appointment = dictfecthall(cursor)

        if request.session.get('role') == 'PENGGUNA_PUBLIK':
            with connection.cursor() as cursor:
                cursor.execute(
                """
                SELECT * FROM SIRUCO.MEMERIKSA M, SIRUCO.PASIEN P
                WHERE M.nik_pasien = P.nik AND P.idPendaftar = '{}';
                """
                .format(username))
                data_appointment = dictfecthall(cursor)

        if request.session.get('role') == 'DOKTER':
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM SIRUCO.MEMERIKSA WHERE username_dokter = '{}';"
                .format(username))
                data_appointment = dictfecthall(cursor)

        return render(request, 'list-appointment.html', {'appointment': data_appointment})

def deleteAppointment(request):
    with connection.cursor() as cursor:
        if request.method == 'GET':
            nik = request.GET.get('nik')
            username = request.GET.get('username')
            kode_faskes = request.GET.get('kode_faskes')
            shift = request.GET.get('shift')
            tanggal = request.GET.get('tanggal')
            print('apa')
            print(nik, username, kode_faskes, shift, tanggal)
            print('apa1')
            with connection.cursor() as cursor:
                cursor.execute("SELECT NoSTR FROM SIRUCO.DOKTER where username='{}' LIMIT 1;".format(username))
                no_str = cursor.fetchone()[0]
                print(no_str)
            print('apa2')
            with connection.cursor() as cursor:
                cursor.execute("SET search_path to SIRUCO;")
                cursor.execute(
                    '''
                    DELETE FROM SIRUCO.MEMERIKSA WHERE nik_pasien='{}' 
                    AND username_dokter='{}' AND nostr='{}' AND kode_faskes= '{}' 
                    AND praktek_shift= '{}' AND praktek_tgl='{}';
                    '''.format(nik, username, no_str, kode_faskes, shift, tanggal))
            print('apa3')
        return redirect('dokter:listAppointment')

def updateAppointment(request):

    with connection.cursor() as cursor:
        print('sebelum set siruco')
        cursor.execute("SET search_path to SIRUCO;")
        print ('before tes dok')
        username = request.session["username"]

        if request.method == 'POST':
            print("masuk post update")
            nik = request.POST.get('nik')
            email = request.POST.get('email')
            kode = request.POST.get('kode_faskes')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')
            rekomendasi = request.POST.get('rekomendasi')
            print(rekomendasi)

            isi = {
                'nik': nik,
                'email': username, 
                'kode_faskes': kode, 
                'tanggal': tanggal,
                'shift': shift,
                'rekomendasi': rekomendasi
                }
         
            try: 
                print('masuk try')
                if rekomendasi is None or rekomendasi == "":
                    raise ValidationError("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu")

                with connection.cursor() as cursor:
                    cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                    cursor.execute("SELECT NoSTR FROM DOKTER where username=%s LIMIT 1;", [email])
                    no_str = cursor.fetchone()[0]
                    
                if no_str is None:
                    print("masuk none yg no str")
                    return redirect('dokter:formAppointment')
                print('tes dokter')
                
                print('tes dokter 2')
                #UPDATE TABLE MEMERIKSA 
                with connection.cursor() as cursor:
                    print("masuk update table")
                    cursor.execute("SET search_path to SIRUCO;")
                    cursor.execute(
                    """
                    UPDATE MEMERIKSA SET rekomendasi= '{}'
                    WHERE nik_pasien='{}' AND username_dokter='{}' 
                    AND kode_faskes= '{}' 
                    AND praktek_shift= '{}' AND praktek_tgl='{}';
                    """
                    .format(
                    rekomendasi, 
                    nik, email, 
                    kode,
                    shift, tanggal))

profilpengguna/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db import connection

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def admin_view(request):
    print ("TEST")
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]   
    # with connection.cursor() as cursor:
        print ("TEST00")
        
        cursor.execute("SELECT username "
                    " FROM AKUN_PENGGUNA WHERE username = '{}';".format(username))
        data_profil = cursor.fetchone()
        print ("TEST01")
        print(data_profil)
        args = {
            'data_profil' : data_profil,
            }
        # print ("TEST02")
        return render(request, 'pp-admin-sistem.html', args)
        
def publik_view(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        # username = request.session["username"] 

        cursor.execute("SELECT * FROM AKUN_PENGGUNA WHERE username=%s",
                       [request.session.get("username")])
        user_data = cursor.fetchone()

        # print("user data ya")
        # print(user_data)
        
        cursor.execute("SELECT * FROM PENGGUNA_PUBLIK WHERE username=%s",
                       [request.session.get("username")])
        role_data = cursor.fetchone()               
        # print(role_data)
        args = {
            'user' : user_data,
            'role' : role_data,
            }
        return render(request, 'pp-publik.html', args)

def dokter_view(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        # username = request.session["username"]
        
        cursor.execute("SELECT * FROM AKUN_PENGGUNA WHERE username=%s",
                       [request.session.get("username")])
        user_data = cursor.fetchone()
        
        cursor.execute("SELECT * FROM DOKTER WHERE username=%s",
                       [request.session.get("username")])
        role_data = cursor.fetchone()               
        
        # cursor.execute("SELECT username, nostr, nama, nohp, gelardepan, gelarbelakang "
        #             " FROM DOKTER WHERE username = '{}';".format(username))

        # data_profil = cursor.fetchone()
        # print(data_profil)
        print(role_data)
        args = {
            'user' : user_data,
            'role' : role_data,
            }
        # print ("TEST02")
        return render(request, 'pp-dokter.html', args)

def satgas_view(request):
    print ("TEST")
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        
        cursor.execute("SELECT * FROM AKUN_PENGGUNA WHERE username=%s",
                       [request.session.get("username")])
        user_data = cursor.fetchone()
        
        cursor.execute("SELECT a.username, a.idfaskes FROM ADMIN_SATGAS a, "
                        " FASKES F WHERE F.kode = a.idfaskes AND "
                        " a.username=%s",
                        [request.session.get("username")])
        role_data = cursor.fetchone()

        # cursor.execute("SELECT kode FROM FASKES WHERE id_faskes=%s",
        #                [request.session.get("username")])
        # idfaskes_data = cursor.fetchone()                         

        print(role_data)

        args = {
            'user' : user_data,
            'role' : role_data,
            # 'faskes': idfaskes_data,
            }
        return render(request, 'pp-admin-satgas.html', args)

        

users/templates/admin_satgas_form.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:regadminsistem' %}">Admin Sistem</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regpenggunappublik' %}">Pengguna Publik</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:regdokter' %}">Dokter</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:regadminsatgas' %}">Admin Satgas</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Admin Satgas</center></h4></p>
      <form action="{% url 'users:regadminsatgas' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Username</label>
          {{ form.username }}
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>


        <div class="input-group mb-3">
          <div class="input-group-prepend">
              <span class="input-group-text"><i class="fa fa-hospital"></i></span>
          </div>
          {{ form.kode_faskes }}
        </div>
        
        
        {% if message is not None %}
        <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
        {{ message }}
        </div>
        {% endif %}
        
        <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>



{% endblock %}

users/templates/admin_sistem_form.html
<!-- ceritanya admin sistem -->

{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'users:regadminsistem' %}">Admin Sistem</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regpenggunappublik' %}">Pengguna Publik</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regdokter' %}">Dokter</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:regadminsatgas' %}">Admin Satgas</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Admin Sistem</center></h4></p>
      <form action="{% url 'users:regadminsistem' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Email</label>
          {{ form.username }}
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>
        
        {% if message is not None %}
          <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
          {{ message }}
          </div>
        {% endif %}

        <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/dokter_form.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regadminsistem' %}">Admin Sistem</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regpenggunappublik' %}">Pengguna Publik</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'users:regdokter' %}">Dokter</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:regadminsatgas' %}">Admin Satgas</a>
          </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Register as Dokter</center></h4></p>
      <form action="{% url 'users:regdokter' %}" method="POST">
        {% csrf_token %}
        <div class="form-group .justify-content-start ">
          <label for="exampleInputEmail1">Username</label>
          {{ form.username }}
        </div>
        
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          {{ form.password }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Nomor STR</label>
          {{ form.nostr }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Nama</label>
          {{ form.nama }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">No HP</label>
          {{ form.nohp }}
        </div>

        <div class="form-group">
          <label for="validationDefault02">Gelar Depan</label>
          {{ form.gelardepan }}
        </div>

        <div class="form-group">
          <label for="validationDefault01">Gelar Belakang</label>
          {{ form.gelarbelakang }}
        </div>

        {% if message is not None %}
        <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
        {{ message }}
        </div>
        {% endif %}
        
        <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
      </form>
      </div>
    </div>
  </div>


{% endblock %}

users/templates/login.html
{% extends "base.html" %}


{% block style_content %}
<style>
    .divlogin{
        margin-top: 80px;
    }
</style>
{% endblock %}

{% block page_content %}


<div class="outer-form divlogin container form-column col-md-4 ">
    <p class="tulisan_login"><h2><center>LOGIN</center></h4></p>
  <form action="{% url 'users:mylogin' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Username</label>
      {{ form.username }}

    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      {{ form.password }}
    </div>
    
    <div style="text-align: center;">
      {% if messages %}
      {% for message in messages %}
      <p {% if message.tags %} class="{{ message.tags }} text-danger"{% endif %}>{{ message }}</p>
      {% endfor %}
      {% endif %}
      
    </div>
    <div class="d-flex justify-content-center">
      

      <input class="btn btn-primary " type="submit" value="Log in">
      
    </div>
    
    
  </form>
</div>
{% endblock %}

users/templates/pengguna_publik_form.html
<!-- ceritanya pengguna_publik -->
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Register Form </center></h1>
<h5> <center> Choose your role first, then fill the form </center></h5>
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regadminsistem' %}">Admin Sistem</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'users:regpenggunappublik' %}">Pengguna Publik</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:regdokter' %}">Dokter</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:regadminsatgas' %}">Admin Satgas</a>
        </li>
      </ul>
    </div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4  ">
        <p class="tulisan_login"><h4><center>Register as Pengguna Publik</center></h4></p>
      <form action="{% url 'users:regpenggunappublik' %}" method="POST">
          {% csrf_token %}
          <div class="form-group .justify-content-start ">
            <label for="exampleInputEmail1">Email</label>
            {{ form.username }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            {{ form.password }}
          </div>

          <div class="form-group">
            <label for="validationDefault01">Nama lengkap</label>
            {{ form.nama }}
          </div>

          <div class="form-group">
            <label for="validationDefault02">NIK</label>
            {{ form.nik }}
          </div>

          <div class="form-group">
            <label for="validationDefault02">No HP</label>
            {{ form.nohp }}
          </div>

          <button type="submit" class="btn btn-primary  btn-am">Sign Up</button>
          <div style="text-align: center;">
          {% if message is not None %}
          <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
          {{ message }}
          </div>
          {% endif %}
          </div>
      </form>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/profil-pengguna.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> BERHASIL YO </center></h1>

{% endblock %}