TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('dokter/', include('dokter.urls')),
    path('pasien/', include('pasien.urls')),
    path('ruanganhotel/', include('ruanganhotel.urls')),
    path('reservasihotel/', include('reservasihotel.urls')),
    path('transaksihotel/', include('transaksihotel.urls')),
    path('transaksibooking/', include('transaksibooking.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('faskes/', include('faskes.urls')),
]

faskes/urls.py
from django.urls import path, include
from . import views

app_name = 'faskes'
urlpatterns = [ 
	path('ReservasiFaskes/', views.ReservasiFaskes, name='ReservasiFaskes'),
    path('listReservasiFaskes/', views.listReservasiFaskes, name='listReservasiFaskes'),
    path('deleteFaskes/', views.deleteFaskes, name='deleteFaskes'),
    path('updateFaskes/', views.updateFaskes, name='updateFaskes'),
    path('detailFaskes/', views.detailFaskes, name='detailFaskes'),
    path('buatJadwalFaskes/', views.buatJadwalFaskes, name='buatJadwalFaskes'),
    path('listJadwalFaskes/', views.listJadwalFaskes, name='listJadwalFaskes'),

]

faskes/models.py
from django.db import models

# Create your models here.

faskes/forms.py
from django import forms
from django.forms import Form, ModelForm
from django.db import connection, transaction, IntegrityError


class reservasiFaskes(forms.Form):
    LIST_NIK = []
    LIST_Tipe = []
    LIST_Status = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT tipe, tipe FROM SIRUCO.FASKES")
            self.fields['tipe'].choices = cursor.fetchall()

            cursor.execute("SELECT DISTINCT statusmilik, statusmilik FROM SIRUCO.FASKES")
            self.fields['statusmilik'].choices = cursor.fetchall()
            # cursor.execute("SELECT Kode_Faskes, Kode_Faskes FROM SIRUCO.RUMAH_SAKIT")
            # self.fields['kode_rs'].choices = cursor.fetchall()
    with connection.cursor() as cursor:
        cursor.execute("SELECT MAX(kode) FROM SIRUCO.FASKES;")
        kode =  cursor.fetchall()[0][0]
        print("CEK KODE")

        kodebaru = str((int(kode)+1))
        print (kodebaru)

    kode = forms.CharField(label='Kode Faskes',  initial= kodebaru, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
    tipe = forms.ChoiceField(label="Tipe", choices= LIST_Tipe, widget=forms.Select(attrs={'class': 'form-control'})) 
    nama = forms.CharField(label="Nama", widget=forms.TextInput(attrs={'class': 'form-control'}))
    statusmilik = forms.ChoiceField(label="Status Kepemilikan", choices= LIST_Status, widget=forms.Select(attrs={'class': 'form-control'})) 
    jalan = forms.CharField(label="Jalan", widget=forms.TextInput(attrs={'class': 'form-control'}))
    kelurahan = forms.CharField(label="Kelurahan",  widget=forms.TextInput(attrs={'class': 'form-control'}))
    kecamatan = forms.CharField(label="Kecamatan", widget=forms.TextInput(attrs={'class': 'form-control'}))
    kabkot = forms.CharField(label="Kabupaten/Kota",  widget=forms.TextInput(attrs={'class': 'form-control'}))
    prov = forms.CharField(label="Provinsi", widget=forms.TextInput(attrs={'class': 'form-control'}))


class UpdateFaskes(forms.Form):
    LIST_Tipe = []
    LIST_Status = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT tipe, tipe FROM SIRUCO.FASKES")
            self.fields['tipe'].choices = cursor.fetchall()

            cursor.execute("SELECT DISTINCT statusmilik, statusmilik FROM SIRUCO.FASKES")
            self.fields['statusmilik'].choices = cursor.fetchall()

    kode = forms.CharField(label='Kode Faskes', widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
    tipe = forms.ChoiceField(label="Tipe", choices= LIST_Tipe, widget=forms.Select(attrs={'class': 'form-control'})) 
    nama = forms.CharField(label="Nama",  widget=forms.TextInput(attrs={'class': 'form-control'}))
    statusmilik = forms.ChoiceField(label="Status Kepemilikan", choices= LIST_Status, widget=forms.Select(attrs={'class': 'form-control'})) 
    jalan = forms.CharField(label="Jalan", widget=forms.TextInput(attrs={'class': 'form-control'}))
    kelurahan = forms.CharField(label="Kelurahan", widget=forms.TextInput(attrs={'class': 'form-control'}))
    kecamatan = forms.CharField(label="Kecamatan", widget=forms.TextInput(attrs={'class': 'form-control'}))
    kabkot = forms.CharField(label="Kabupaten/Kota",  widget=forms.TextInput(attrs={'class': 'form-control'}))
    prov = forms.CharField(label="Provinsi",  widget=forms.TextInput(attrs={'class': 'form-control'}))



class DateInput (forms.DateInput):
    input_type = 'date'

class reservasiJadwalFaskes(forms.Form):
    LIST_Faskes = []
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT kode, kode FROM SIRUCO.FASKES")
            self.fields['kode'].choices = cursor.fetchall()

    kode = forms.ChoiceField(label="Faskes", choices= LIST_Faskes, widget=forms.Select(attrs={'class': 'form-control'})) 
    shift = forms.CharField(label="Shift",  widget=forms.TextInput(attrs={'class': 'form-control'}))
    tanggal = forms.DateField(label="Tanggal", widget=DateInput)

faskes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sessions.models import Session
from django.db import connection, transaction, IntegrityError
from .forms import reservasiFaskes, UpdateFaskes, reservasiJadwalFaskes
from django.core import serializers
from django.http import JsonResponse, HttpResponseRedirect
from homepage.views import user_login_required 
from django.urls import reverse
from users.views import getrole
from django.db import connection

def dictfecthall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row)) 
        for row in cursor.fetchall()
    ]

def ReservasiFaskes(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"] 
        role = request.session.get('role') 

        formbaru = reservasiFaskes()


        if request.method == 'POST':
            form = reservasiFaskes(request.POST)
            if form.is_valid():
                kode = request.POST.get('kode')
                tipe = request.POST.get('tipe')
                nama = request.POST.get('nama')
                statusmilik = request.POST.get('statusmilik')
                jalan = request.POST.get('jalan')
                kelurahan = request.POST.get('kelurahan')
                kecamatan = request.POST.get('kecamatan')
                kabkot = request.POST.get('kabkot')
                prov = request.POST.get('prov')

                cursor.execute("SET search_path TO SIRUCO;")
                cursor.execute("INSERT INTO FASKES "
                                "VALUES ('{}', '{}', '{}', '{}', '{}','{}','{}','{}','{}');"
                                .format(kode,tipe,nama,statusmilik,jalan,kelurahan,kecamatan,kabkot,prov))

                return redirect('faskes:listReservasiFaskes')

        print("masuk sini")
        return render(request, 'reservasi-faskes.html', {'form': formbaru})


def listReservasiFaskes(request): 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"] 
        role = request.session.get('role') 

        
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.FASKES")
            list_faskes = dictfecthall(cursor)
        return render(request, 'list-faskes.html', {'listreservasi': list_faskes})

        # else :
        #     with connection.cursor() as cursor:
        #         cursor.execute("SELECT * FROM SIRUCO.FASKES, SIRUCO.FASKES")
        #         list_reservasi = dictfecthall(cursor)
        #     return render(request, 'list-faskes.html', {'listreservasi': list_faskes})

def deleteFaskes(request): 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]
    
        if request.method == 'GET':
            kode = request.GET.get('kode')
            tipe = request.GET.get('tipe')

        
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM SIRUCO.FASKES WHERE kode='{}';".format(kode))
    
    return redirect('faskes:listReservasiFaskes')

        

def updateFaskes(request): 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]

        if request.method == 'POST':
            form = UpdateFaskes(request.POST)
            if form.is_valid():
                kode = request.POST.get('kode')
                tipe = request.POST.get('tipe')
                nama = request.POST.get('nama')
                statusmilik = request.POST.get('statusmilik')
                jalan = request.POST.get('jalan')
                kelurahan = request.POST.get('kelurahan')
                kecamatan = request.POST.get('kecamatan')
                kabkot = request.POST.get('kabkot')
                prov = request.POST.get('prov')
                
                with connection.cursor() as cursor:
                    cursor.execute("SET search_path to SIRUCO;")
                    cursor.execute(
                    """
                    UPDATE FASKES SET tipe= '{}',
                    nama= '{}',
                    statusmilik= '{}',
                    jalan= '{}',
                    kelurahan= '{}',
                    kecamatan= '{}',
                    kabkot= '{}',
                    prov= '{}'
                    WHERE kode='{}';
                    """
                    .format(tipe,nama,statusmilik,jalan,kelurahan,kecamatan,kabkot,prov,kode))
                
                return redirect('faskes:listReservasiFaskes')

        
        elif request.method == 'GET':
            kode = request.GET.get('kode')
            
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM SIRUCO.FASKES WHERE kode='{}';".format(kode))
                list_faskes = dictfecthall(cursor)[0]

                isi = {'kode': list_faskes["kode"], 
                    'tipe': list_faskes["tipe"], 
                    'nama': list_faskes["nama"],
                    'statusmilik': list_faskes["statusmilik"],
                    'jalan': list_faskes["jalan"],
                    'kelurahan': list_faskes["kelurahan"],
                    'kecamatan': list_faskes["kecamatan"],
                    'kabkot': list_faskes["kabkot"],
                    'prov': list_faskes["prov"],
                }

    

            # if isi is None:
            #     print("update isi none")
            #     return redirect('dokter:listAppointment')

                form=UpdateFaskes(initial=isi)
            return render(request, 'update-Faskes.html', {'form': form}) 


def detailFaskes(request): 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]

    if request.method == 'GET':
        kode = request.GET.get('kode')
        tipe = request.GET.get('tipe')

    
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.FASKES WHERE kode='{}';".format(kode))
        data_faskes = dictfecthall(cursor)[0]
        print (data_faskes)

    return render(request, 'detail-faskes.html', {'data_faskes' : data_faskes})

def listJadwalFaskes(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]  
        print(username)

    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.JADWAL;")
        jadwal = dictfecthall(cursor)
    return render(request, 'list-jadwalfaskes.html', {'jadwal': jadwal})

def buatJadwalFaskes(request): 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]

    formbaru = reservasiJadwalFaskes()
    if request.method == 'POST':
        form = reservasiJadwalFaskes(request.POST)
        if form.is_valid():
            kode = request.POST.get('kode')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')

            with connection.cursor() as cursor:
                cursor.execute("SET search_path TO SIRUCO;")
                cursor.execute(
                    """
                    INSERT INTO Jadwal 
                    VALUES ('{}','{}','{}');
                    """
                    .format(kode,shift,tanggal))

            return redirect('faskes:listJadwalFaskes')

    return render(request, 'reservasi-jadwalfaskes.html', {'form': formbaru})

faskes/templates/detail-faskes.html
{% extends "base.html" %}

{% block page_content %}

<body>
    <div style="margin-top: 40px;" class="outer-form container">
        <h2><center>DETAIL FASKES</center></h2>
        <div style="margin-top: 15px;" class="container">
            <p>Kode Faskes          : {{ data_faskes.kode }}</p>
            <p>Tipe                 : {{ data_faskes.tipe }}</p>
            <p>Nama Faskes          : {{ data_faskes.nama }}</p>
            <p>Status Kepemilikan   : {{ data_faskes.statusmilik }}</p>
            
            <h3>Alamat              : </h3>
            <p>Jalan                : {{ data_faskes.jalan }}</p>
            <p>Kelurahan            : {{ data_faskes.kelurahan }}</p>
            <p>Kecamatan            : {{ data_faskes.kecamatan }}</p>
            <p>Kabupaten/Kota       : {{ data_faskes.kabkot }}</p>
            <p>Provinsi             : {{ data_faskes.prov }}</p>
        </div>
        <form action="{% url 'faskes:listReservasiFaskes' %}" method="GET">
            <input type="submit" class="btn btn-outline-primary" value="Kembali">
        </form>
    </div>

 
</body>
{% endblock %}

faskes/templates/list-faskes.html
{% extends 'base.html' %}

{% block page_content %}

<h1 class="mt-4"> <center> List Faskes </center></h1>
<br>

<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover  justify-content-center" align="center" style="text-align: center;">
		<thead class="thead-dark">
			
            <th>Kode Faskes</th>
            <th>Tipe</th>
            <th>Nama Faskes</th>

            {% if request.session.role == 'ADMIN_SATGAS' %}
            <th>Action</th>
            {% endif %}

		</thead>
		{% for isi in listreservasi %}

		<tr>
            
            <td>{{ isi.kode }}</td>
            <td>{{ isi.tipe }}</td>
            <td>{{ isi.nama }}</td>


            {% if request.session.role == 'ADMIN_SATGAS'  %}
            
                <td>
                    <form action="{% url 'faskes:detailFaskes' %}" method="GET">
                        <input type="hidden" id="kode" name="kode" value="{{ isi.kode }}">
                        <input type="hidden" id="tipe" name="tipe" value="{{ isi.tipe }}">
                        <input type="hidden" id="nama" name="nama" value="{{ isi.nama }}">
                        <input type="submit" class="btn btn-info" value="Detail">
                    </form>
                    
                    <br>
                    <form action="{% url 'faskes:deleteFaskes' %}" method="GET">
                        <input type="hidden" id="kode" name="kode" value="{{ isi.kode }}">
                        <input type="hidden" id="tipe" name="tipe" value="{{ isi.tipe }}">
                        <input type="hidden" id="nama" name="nama" value="{{ isi.nama }}">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                    
                    <br>
                    <form action="{% url 'faskes:updateFaskes' %}" method="GET">
                        <input type="hidden" id="kode" name="kode" value="{{ isi.kode }}">
                        <input type="hidden" id="tipe" name="tipe" value="{{ isi.tipe }}">
                        <input type="hidden" id="nama" name="nama" value="{{ isi.nama }}">
                        <input type="submit" class="btn btn-success" value="Update">
                    </form>
                </td>
                
            {% endif %}
            
        </tr>
        {% endfor %}
    </table>		
</div>

{% endblock page_content %}

faskes/templates/list-jadwalfaskes.html
{% extends 'base.html' %}

{% block page_content %}

<h1 class="mt-4"> <center> List Jadwal Faskes </center></h1>
<br>

<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover  justify-content-center" align="center" style="text-align: center;">
		<thead class="thead-dark">
			
				<th>No.</th>
				<th>Faskes</th>
				<th>Shift</th>
				<th>Tanggal</th>


		</thead>
		{% for isi in jadwal %}

		<tr>
            
            <td>{{ forloop.counter }}</td>
            <td>{{ isi.kode_faskes  }}</td>
            <td>{{ isi.shift  }}</td>
            <td>{{ isi.tanggal | date:'d-m-Y' }}</td>

            
        </tr>
        {% endfor %}
    </table>		
</div>

{% endblock page_content %}

faskes/templates/reservasi-faskes.html
{% extends 'base.html' %}

{% block page_content %}
<h1 class="mt-4"> <center> Reservasi Rumah Sakit </center></h1>
<br>
<div class="container d-flex justify-content-center" align="center">

    <form action="{% url 'faskes:ReservasiFaskes' %}" method="post">
        {% csrf_token %}

        <div class="form-group">

            <h4>{{ form.kode.label }}</h4>
                {{ form.kode }}

            <h4>{{ form.tipe.label }}</h4>
                {{ form.tipe }}

            <h4>{{ form.nama.label }}</h4> 
                {{ form.nama }}

            <h4>{{ form.statusmilik.label }}</h4>
                {{ form.statusmilik }}
                
            <h4>Alamat:</h4>
            <h4>{{ form.jalan.label }}</h4>
                {{ form.jalan }}  

            <h4>{{ form.kelurahan.label }}</h4>
                {{ form.kelurahan }}

            <h4>{{ form.kecamatan.label }}</h4>
                {{ form.kecamatan }}

            <h4>{{ form.kabkot.label }}</h4> 
                {{ form.kabkot }}

            <h4>{{ form.prov.label }}</h4>
                {{ form.prov }}
            

            </div>
        <input class="btn btn-outline-primary" type="submit" value="Simpan">

        </form>
    
</div> 

{% endblock %}

faskes/templates/reservasi-jadwalfaskes.html
{% extends 'base.html' %}

{% block page_content %}
<h1 class="mt-4"> <center> Reservasi Jadwal Faskes </center></h1>
<br>
<div class="container d-flex justify-content-center" align="center">

    <form action="{% url 'faskes:buatJadwalFaskes' %}" method="post">
        {% csrf_token %}

        <div class="form-group">

            <h4>{{ form.kode.label }}</h4>
                {{ form.kode }}

            <h4>{{ form.shift.label }}</h4>
                {{ form.shift }}

            <h4>{{ form.tanggal.label }}</h4> 
                {{ form.tanggal }}

            </div>
        <input class="btn btn-outline-primary" type="submit" value="Simpan">

        </form>
    
</div> 

{% endblock %}

faskes/templates/update-Faskes.html
{% extends 'base.html' %}

{% block page_content %}
<h1> <center> Update Faskes </center></h1>
{% if message is not None %}
    <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
    {{ message }}
    </div>
{% endif %}
<div class="container d-flex justify-content-center" align="center">
    <form action="{% url 'faskes:updateFaskes' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="validationDefault02">{{ form.kode.label }}</label>
            {{ form.kode }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.tipe.label }}</label>
            {{ form.tipe }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.nama.label }}</label>
            {{ form.nama }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.statusmilik.label }}</label>
            {{ form.statusmilik }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.jalan.label }}</label>
            {{ form.jalan }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.kelurahan.label }}</label>
            {{ form.kelurahan }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.kecamatan.label }}</label>
            {{ form.kecamatan }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.kabkot.label }}</label>
            {{ form.kabkot }}
        </div>

        <div class="form-group">
            <label for="validationDefault02">{{ form.prov.label }}</label>
            {{ form.prov }}
        </div>

        <input class="btn btn-outline-primary" type="submit" value="Simpan">

    </form>
</div>
{% endblock page_content %}