TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('dokter/', include('dokter.urls')),
    path('pasien/', include('pasien.urls')),
    path('ruanganhotel/', include('ruanganhotel.urls')),
    path('reservasihotel/', include('reservasihotel.urls')),
    path('transaksihotel/', include('transaksihotel.urls')),
    path('transaksibooking/', include('transaksibooking.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('faskes/', include('faskes.urls')),
]

dokter/urls.py
from django.urls import path, include
from . import views

app_name = 'dokter'
urlpatterns = [ 
	path('createAppointment/', views.createAppointment, name='createAppointment'),
    path('formAppointment/', views.formAppointment, name='formAppointment'),
    path('listAppointment/', views.listAppointment, name='listAppointment'),
    path('deleteAppointment/', views.deleteAppointment, name='deleteAppointment'),
    path('updateAppointment/', views.updateAppointment, name='updateAppointment'),
    path('ajaxAppointment/', views.ajaxAppointment, name='ajaxAppointment'),

    path('createJadwal/', views.createJadwal, name='createJadwal'),
    path('readJadwal/', views.readJadwal, name='readJadwal'),
    path('listJadwal/', views.listJadwal, name='listJadwal'),

	path('createRuanganRS/', views.createRuanganRS, name='createRuanganRS'),
    path('listRuanganRS/', views.listRuanganRS, name='listRuanganRS'),
    path('updateRuanganRS/', views.updateRuanganRS, name='updateRuanganRS'),
    path('ajaxKodeRS/', views.ajaxKodeRS, name='ajaxKodeRS'),
	path('ajaxRuanganRS/', views.ajaxRuanganRS, name='ajaxRuanganRS'),

    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('listBedRS/', views.listBedRS, name='listBedRS'),
    path('deleteBedRS/', views.deleteBedRS, name='deleteBedRS'),
    path('ajaxRuanganBed/', views.ajaxRuanganBed, name='ajaxRuanganBed'),
	path('ajaxKodeBed/', views.ajaxKodeBed, name='ajaxKodeBed'),

]

faskes/urls.py
from django.urls import path, include
from . import views

app_name = 'faskes'
urlpatterns = [ 
	path('ReservasiFaskes/', views.ReservasiFaskes, name='ReservasiFaskes'),
    path('listReservasiFaskes/', views.listReservasiFaskes, name='listReservasiFaskes'),
    path('deleteFaskes/', views.deleteFaskes, name='deleteFaskes'),
    path('updateFaskes/', views.updateFaskes, name='updateFaskes'),
    path('detailFaskes/', views.detailFaskes, name='detailFaskes'),
    path('buatJadwalFaskes/', views.buatJadwalFaskes, name='buatJadwalFaskes'),
    path('listJadwalFaskes/', views.listJadwalFaskes, name='listJadwalFaskes'),

]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage_view, name='myhomepage'),
    path('landingpage/', views.landing_view, name='landingpage'),
]

pasien/urls.py
from django.urls import path, include
from . import views

app_name = 'pasien'
urlpatterns = [ 
    path('create/', views.pasien_form_view, name='create-pasien'),
    path('list/', views.list_pasien, name='list-pasien'),
    path('detailPasien/', views.detailPasien, name='detailPasien'),
    path('deletePasien/', views.deletePasien, name='deletePasien'),
    path('updatePasien/', views.updatePasien, name='updatePasien'),
    # path('detail-pasien/<id>', views.detail_pasien, name='detail_pasien'),
    # path('delete-pasien/<id>', views.delete_pasien, name='delete_pasien<id>'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.user_login, name='mylogin'),
    path('register/adminsistem/', views.admin_sistem_view, name='regadminsistem'),
    path('register/penggunapublik/', views.pengguna_publik_form_view, name='regpenggunappublik'),
    path('register/dokter/', views.dokter_form_view, name='regdokter'),
    path('register/adminsatgas/', views.admin_satgas_form_view, name='regadminsatgas'),
    path('logout/', views.userLogout, name='logout'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.core.paginator import Paginator
from django.http import HttpResponse

# Create your views here.
def homepage_view(request):
    return render(request, 'homepage.html')

def landing_view(request):
    return render(request, 'landingpage.html')

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        username = request.session.get('username')
        if username is None:
            return redirect('users:mylogin')
        else:
            return function(request, *args, **kwargs)
    return wrapper

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>SIRUCO B6</title>
        {% block style_content %}

        {% endblock %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-white text-danger">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse justify-content-end collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">


                    {% if request.session.username %}
                        {% if request.session.role != 'ADMIN' %}
                          <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pasien
                          </a>
                        
                          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          {% if request.session.role == 'PENGGUNA_PUBLIK' %}
                            <a class="dropdown-item" href="{% url 'pasien:create-pasien' %}">Pendaftaran Pasien</a>
                            <a class="dropdown-item" href="{% url 'pasien:list-pasien' %}">List Pasien</a>
                          {% endif %}
                        
                          {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' %}
                            <a class="dropdown-item" href="{% url 'dokter:createAppointment' %}">Buat Appointment</a>

                          {% endif %}

                          {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' or request.session.role == 'DOKTER' %}
                            <a class="dropdown-item" href="{% url 'dokter:listAppointment' %}">List Appointment</a>
                            
                            <a class="dropdown-item" href="#">List Hasil Tes Pasien</a>
                          {% endif %}

                        {% if request.session.role == 'DOKTER' %}
                        <a class="dropdown-item" href="#">Buat Hasil Tes Pasien</a>
                        {% endif %}
                        </div>
                        </li>
                        {% endif %}


                        {% if request.session.role != 'ADMIN' %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Rumah Sakit
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == 'ADMIN_SATGAS' %}
                        <a class="dropdown-item" href="{% url 'rumahsakit:reservasiRS' %}">Buat RS</a>
                        <a class="dropdown-item" href="{% url 'rumahsakit:listReservasiRS' %}">List RS</a>
                        <a class="dropdown-item" href="{% url 'dokter:createRuanganRS' %}">Buat Ruangan RS</a>
                        <a class="dropdown-item" href="{% url 'dokter:listRuanganRS' %}">List Ruangan RS</a>
                        <a class="dropdown-item" href="{% url 'dokter:createBedRS' %}">Buat Bed RS</a>
                        <a class="dropdown-item" href="{% url 'dokter:listBedRS' %}">List Bed RS</a>                
                        <a class="dropdown-item" href="{% url 'reservasihotel:formReservasiHotel' %}">Buat Reservasi RS</a>
                        {% endif %}
                        
                        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' %}
                        <a class="dropdown-item" href="{% url 'rumahsakit:listReservasiRS' %}">List Reservasi RS</a>
                        {% endif %}

                        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' or request.session.role == 'DOKTER' %}
                        <a class="dropdown-item" href="{% url 'dokter:listJadwal' %}">List Jadwal Dokter</a>
                        {% endif %}

                        {% if request.session.role == 'DOKTER' %}
                        <a class="dropdown-item" href="{% url 'dokter:readJadwal' %}">Buat Jadwal Dokter</a>
                        {% endif %}
                        </div>
                        </li>
                        {% endif %}

                        {% if request.session.role != 'DOKTER' %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hotel
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == 'ADMIN' %}
                        <!-- <a class="dropdown-item" href="#">Buat Hotel</a>
                        <a class="dropdown-item" href="#">List Hotel</a> -->
                        <a class="dropdown-item" href="{% url 'ruanganhotel:formHotelRoom' %}">Buat Ruangan Hotel</a>
                        <a class="dropdown-item" href="{% url 'ruanganhotel:listHotelRoom' %}">List Ruangan Hotel</a>
                        <!-- <a class="dropdown-item" href="#">Buat Paket Makan</a>
                        <a class="dropdown-item" href="#">List Paket Makan</a>         -->
                        {% endif %}
                        
                        {% if request.session.role == 'PENGGUNA_PUBLIK' %}
                        <!-- <a class="dropdown-item" href="#">List Hotel</a> -->
                        <a class="dropdown-item" href="{% url 'ruanganhotel:listHotelRoom' %}">List Ruangan Hotel</a>
                        <!-- <a class="dropdown-item" href="#">List Paket Makan</a> -->
                        <a class="dropdown-item" href="{% url 'reservasihotel:formReservasiHotel' %}">Buat Reservasi Hotel</a>
                        <a class="dropdown-item" href="{% url 'reservasihotel:listReservasiHotel' %}">List Reservasi Hotel</a>
                        {% endif %}

                        {% if request.session.role == 'ADMIN_SATGAS' %}
                        <a class="dropdown-item" href="{% url 'ruanganhotel:listHotelRoom' %}">List Ruangan Hotel</a>
                        <a class="dropdown-item" href="{% url 'reservasihotel:formReservasiHotel' %}">Buat Reservasi Hotel</a>
                        <a class="dropdown-item" href="{% url 'reservasihotel:listReservasiHotel' %}">List Reservasi Hotel</a>
                        {% endif %}
                        </div>
                        </li>
                        {% endif %}

                        {% if request.session.role == 'ADMIN_SATGAS' or request.session.role == 'PENGGUNA_PUBLIK' %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Transaksi
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.session.role == 'ADMIN_SATGAS' %}
                        <a class="dropdown-item" href="{% url 'rumahsakit:transaksiRS' %}">List Transaksi RS</a>
                        <a class="dropdown-item" href="{% url 'transaksihotel:listTransaksiHotel' %}">List Transaksi Hotel</a>
                        <a class="dropdown-item" href="{% url 'transaksibooking:listTransaksiBooking' %}">List Transaksi Booking Hotel</a>
                        <a class="dropdown-item" href="#">Buat Transaksi Makan dan Daftar Pesan</a>
                        <a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a>
                        {% endif %}
                        
                        {% if request.session.role == 'PENGGUNA_PUBLIK' %}
                        <a class="dropdown-item" href="#">Bayar Transaksi RS</a>
                        <a class="dropdown-item" href="#">Bayar Transaksi Hotel</a>
                        <a class="dropdown-item" href="{% url 'transaksibooking:listTransaksiBooking' %}">List Transaksi Booking Hotel</a>
                        <a class="dropdown-item" href="#">Buat Transaksi Makan dan Daftar Pesan</a>
                        <a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a>
                        {% endif %}
                        </div>
                        </li>
                        {% endif %}

                        {% if request.session.role == 'ADMIN_SATGAS' %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Faskes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'faskes:ReservasiFaskes' %}">Buat Faskes</a>
                        <a class="dropdown-item" href="{% url 'faskes:listReservasiFaskes' %}">List Faskes</a>
                        <a class="dropdown-item" href="{% url 'faskes:buatJadwalFaskes' %}">Buat Jadwal Faskes</a>
                        <a class="dropdown-item" href="{% url 'faskes:listJadwalFaskes' %}">List Jadwal Faskes</a>
                        {% endif %}
                        </div>
                        </li>
  
                        <a class="nav-link text-danger" href="{% url 'users:logout' %}">Logout</a>
                        
                        {% endif %}
                    </ul>
                            

                    {% block navbar_content %}

                    {% endblock %}
                  </ul>
                </div>
              </nav>
        </header>
        {% block page_content %}

        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/Schttp://127.0.0.1:8000/QsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% block script_content %}

        {% endblock %}
    </body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}



<div class="main">
  <div class="container-fluid" style="max-height: 90vh; margin-top: 15%;">
    <div class="p-5 col-lg-12 col-md-6 col-sm-12 flex-column " style="text-align: center">
      <div class="welcome1" >
          <h2 class="mb-2">SIRUCO</h2>
      </div>
    
      <div class="welcome2 mb-3 text2 typewriter">
          <p>We serve the best for you and keep you to <span class ="orange"><strong>#StayAtHome </strong></span></p>
      </div>
    
      <div class="cta-but d-flex flex-row justify-content-center">
        <a href="{% url 'users:mylogin' %}">
          <button class="btn btn-primary mr-2 my-2 my-sm-0 rounded-lg btn-login"  type="submit">Login</button>
        </a>
        <a href="{% url 'users:regadminsistem' %}">
          <button class="btn btn-outline-primary my-2 my-sm-0 rounded-lg btn-register" type="submit">Register</button>     
        </a>
      </div>
    </div>
  </div>
  
</div>

{% endblock %}

homepage/templates/landingpage.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<div class="col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center align-items-left flex-column text-welcome">
  <div class="welcome1">
      <h2 class="mb-3 text1">Welcome to <br>Siruco</h2>
  </div>
  <div class="welcome2 mb-3 text2 typewriter">
      <p>We serve the best for you and keep you to <span class ="orange"><strong>#StayAtHome </strong></span></p>
  </div>
</div>

<div class="col-lg-6 col-md-6 col-sm-12 d-flex align-items-right flex-column">
<img class="kanan img-responsive" src="{% static 'gambarhomepage.jpg' %}">
</div>

{% endblock %}