TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('users/', include('users.urls')),
    path('profile/',include('profilpengguna.urls')),
    path('dokter/', include('dokter.urls')),
    path('pasien/', include('pasien.urls')),
    path('ruanganhotel/', include('ruanganhotel.urls')),
    path('reservasihotel/', include('reservasihotel.urls')),
    path('transaksihotel/', include('transaksihotel.urls')),
    path('transaksibooking/', include('transaksibooking.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('faskes/', include('faskes.urls')),
]

dokter/urls.py
from django.urls import path, include
from . import views

app_name = 'dokter'
urlpatterns = [ 
	path('createAppointment/', views.createAppointment, name='createAppointment'),
    path('formAppointment/', views.formAppointment, name='formAppointment'),
    path('listAppointment/', views.listAppointment, name='listAppointment'),
    path('deleteAppointment/', views.deleteAppointment, name='deleteAppointment'),
    path('updateAppointment/', views.updateAppointment, name='updateAppointment'),
    path('ajaxAppointment/', views.ajaxAppointment, name='ajaxAppointment'),

    path('createJadwal/', views.createJadwal, name='createJadwal'),
    path('readJadwal/', views.readJadwal, name='readJadwal'),
    path('listJadwal/', views.listJadwal, name='listJadwal'),

	path('createRuanganRS/', views.createRuanganRS, name='createRuanganRS'),
    path('listRuanganRS/', views.listRuanganRS, name='listRuanganRS'),
    path('updateRuanganRS/', views.updateRuanganRS, name='updateRuanganRS'),
    path('ajaxKodeRS/', views.ajaxKodeRS, name='ajaxKodeRS'),
	path('ajaxRuanganRS/', views.ajaxRuanganRS, name='ajaxRuanganRS'),

    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('listBedRS/', views.listBedRS, name='listBedRS'),
    path('deleteBedRS/', views.deleteBedRS, name='deleteBedRS'),
    path('ajaxRuanganBed/', views.ajaxRuanganBed, name='ajaxRuanganBed'),
	path('ajaxKodeBed/', views.ajaxKodeBed, name='ajaxKodeBed'),

]

dokter/models.py
from django.db import models

# Create your models here.

dokter/forms.py
from django import forms
from django.forms import Form
from django.db import connection, transaction, IntegrityError

class CreateAppointment(forms.Form):
    LIST_NIK= []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT NIK, NIK FROM SIRUCO.PASIEN")
            self.fields['nik'].choices = cursor.fetchall()

    nik = forms.ChoiceField(label='NIK Pasien',  choices= LIST_NIK, widget=forms.Select(attrs={'class': 'form-control'}))
    email = forms.CharField(label="Email Dokter",  widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
    kode_faskes = forms.CharField(label="Kode Faskes", widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
    tanggal = forms.CharField(label="Tanggal Praktek",  widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))   
    shift = forms.CharField(label="Shift Praktek",  widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))

class UpdateAppointment(forms.Form):
	nik = forms.CharField(label="NIK Pasien", required=False, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
	email = forms.CharField(label="Email Dokter", required=False, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
	kode_faskes = forms.CharField(label="Kode Faskes", required=False, max_length=10, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
	tanggal = forms.CharField(label="Tanggal Praktek", required=False, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))   
	shift = forms.CharField(label="Shift Praktek", required=False, widget=forms.TextInput(attrs={'class': 'form-control','readonly': True}))
	rekomendasi = forms.CharField(label="Rekomendasi", required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

class CreateRuanganRS(forms.Form):
    harga_ruangan = forms.CharField(label="Harga Ruangan", required=True, max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipe = forms.CharField(label="Tipe", required=True, max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))  

class UpdateRuanganRS(forms.Form):
    koders = forms.CharField(label='Kode Rumah Sakit', required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    koderuangan = forms.CharField(label="Kode Ruangan", required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    harga = forms.CharField(label="Harga Ruangan", required=True, max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipe = forms.CharField(label="Tipe", required=True, max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))

class CreateBedRS(forms.Form):
	KODE_RS_CHOICES = []

	kode_rs = forms.ChoiceField(label='Kode Rumah Sakit', required=True, choices= KODE_RS_CHOICES, widget=forms.Select(attrs={
		'class': 'form-control',
		'id' : 'kode_rs',
		'required' : True}))

	def __init__(self, *args, **kwargs):
		super(CreateBedRS, self).__init__(*args, **kwargs)
		with connection.cursor() as cursor:
			cursor.execute("SELECT Kode_Faskes, Kode_Faskes FROM SIRUCO.RUMAH_SAKIT")
			self.fields['kode_rs'].choices = cursor.fetchall()

dokter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sessions.models import Session
from django.db import connection, transaction, IntegrityError
from .forms import *
from django.core import serializers
from django.http import JsonResponse, HttpResponseRedirect
from homepage.views import user_login_required 
from django.urls import reverse
from users.views import getrole
from django.db import connection
import datetime

def dictfecthall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row)) 
        for row in cursor.fetchall()
        ]

#APPOINTMENT ------------------------------------------------------------------------------------------------------
def createAppointment(request):
    # print (getrole)
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]  
        print(username) 
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.JADWAL_DOKTER")
        data_appointment = dictfecthall(cursor)
    return render(request, 'create-appointment.html', {'appointment': data_appointment})

def formAppointment(request): 
    with connection.cursor() as cursor:
        print('sebelum set siruco')
        cursor.execute("SET search_path to SIRUCO;")
        print ('before tes dok')
        username = request.session["username"]
        
        if request.method == 'POST':
            # form = createAppointment(request.POST)
            # if form.is_valid():
            nik = request.POST.get('nik_pasien')
            email = request.POST.get('email')
            kode = request.POST.get('kode_faskes')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')
            rekomendasi = '...'
            print(nik)
            isi = {'email': email, 
                'kode_faskes': kode, 
                'tanggal': tanggal,
                'shift': shift}

            with connection.cursor() as cursor:
                cursor.execute("SELECT NoSTR FROM SIRUCO.DOKTER where username=%s LIMIT 1;", [email])
                no_str = cursor.fetchone()[0]
                print(no_str)
                
            if no_str is None:
                return redirect('dokter:formAppointment')
            print('tes dokter')
            try: 
                print('tes dokter 2')
            #Insert into MEMERIKSA 
                with connection.cursor() as cursor:
                    
                    print('tes dok')
                    cursor.execute("SET search_path TO SIRUCO;")
                    print(nik, no_str, email, kode, shift, tanggal, rekomendasi)
                    cursor.execute("INSERT INTO MEMERIKSA "
                                    "VALUES ('{}', '{}', '{}', '{}', '{}','{}', '{}');"
                                    .format(nik, no_str, email, kode, shift, tanggal, rekomendasi))
                    print('tes dokk')
                
                return redirect('dokter:listAppointment')

            except: 
                print('tes dokter 3')
                form=CreateAppointment(initial=isi)
                return render(request, 'form-appointment.html', 
                {'form': form, 'message': 'Tidak bisa membuat perjanjian dengan dokter, silahkan pilih jadwal lainnya.'})
        
        elif request.method == 'GET':
            print('tes dokter 4')
            username = request.GET.get('username')
            kode_faskes = request.GET.get('kode_faskes')
            shift = request.GET.get('shift')
            tanggal = request.GET.get('tanggal')
            print(username, kode_faskes, shift, tanggal)

            isi = {
                'email': username, 
                'kode_faskes': kode_faskes, 
                'tanggal': tanggal,
                'shift': shift} 

            print(isi)
            if username is None or kode_faskes is None or shift is None or tanggal is None:
                print("masuk none yg atas")
                return redirect('dokter:createAppointment')

            if isi is None:
                return redirect('dokter:createAppointment')

            form=CreateAppointment(initial=isi)
        return render(request, 'form-appointment.html', {'form': form})

def ajaxAppointment(request):
    print("MASUK AJAX")
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        pendaftar = request.session["username"]  
    print(pendaftar)
    if request.session.get("role") == "PENGGUNA_PUBLIK":
        with connection.cursor() as cursor:
            cursor.execute("SELECT NIK, NIK FROM SIRUCO.PASIEN where IdPendaftar = %s", [pendaftar])
            data = cursor.fetchall()
    else:
        print('masuk else ajax')
        with connection.cursor() as cursor:
            cursor.execute("SELECT NIK, NIK FROM SIRUCO.PASIEN")
            data = cursor.fetchall()
    nik_pasien = []
    for i in data:
        nik_pasien.append(i[0])
    print(nik_pasien)
    return JsonResponse({'id': nik_pasien})

def listAppointment(request) : 
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to SIRUCO;")
        username = request.session["username"]  
        print(username)

        if request.session.get('role') == 'ADMIN_SATGAS':
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM SIRUCO.MEMERIKSA;")
                data_appointment = dictfecthall(cursor)

        if request.session.get('role') == 'PENGGUNA_PUBLIK':
            with connection.cursor() as cursor:
                cursor.execute(
                """
                SELECT * FROM SIRUCO.MEMERIKSA M, SIRUCO.PASIEN P
                WHERE M.nik_pasien = P.nik AND P.idPendaftar = '{}';
                """
                .format(username))
                data_appointment = dictfecthall(cursor)

        if request.session.get('role') == 'DOKTER':
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM SIRUCO.MEMERIKSA WHERE username_dokter = '{}';"
                .format(username))
                data_appointment = dictfecthall(cursor)

        return render(request, 'list-appointment.html', {'appointment': data_appointment})

def deleteAppointment(request):
    with connection.cursor() as cursor:
        if request.method == 'GET':
            nik = request.GET.get('nik')
            username = request.GET.get('username')
            kode_faskes = request.GET.get('kode_faskes')
            shift = request.GET.get('shift')
            tanggal = request.GET.get('tanggal')
            print('apa')
            print(nik, username, kode_faskes, shift, tanggal)
            print('apa1')
            with connection.cursor() as cursor:
                cursor.execute("SELECT NoSTR FROM SIRUCO.DOKTER where username='{}' LIMIT 1;".format(username))
                no_str = cursor.fetchone()[0]
                print(no_str)
            print('apa2')
            with connection.cursor() as cursor:
                cursor.execute("SET search_path to SIRUCO;")
                cursor.execute(
                    '''
                    DELETE FROM SIRUCO.MEMERIKSA WHERE nik_pasien='{}' 
                    AND username_dokter='{}' AND nostr='{}' AND kode_faskes= '{}' 
                    AND praktek_shift= '{}' AND praktek_tgl='{}';
                    '''.format(nik, username, no_str, kode_faskes, shift, tanggal))
            print('apa3')
        return redirect('dokter:listAppointment')

def updateAppointment(request):

    with connection.cursor() as cursor:
        print('sebelum set siruco')
        cursor.execute("SET search_path to SIRUCO;")
        print ('before tes dok')
        username = request.session["username"]

        if request.method == 'POST':
            print("masuk post update")
            nik = request.POST.get('nik')
            email = request.POST.get('email')
            kode = request.POST.get('kode_faskes')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')
            rekomendasi = request.POST.get('rekomendasi')
            print(rekomendasi)

            isi = {
                'nik': nik,
                'email': username, 
                'kode_faskes': kode, 
                'tanggal': tanggal,
                'shift': shift,
                'rekomendasi': rekomendasi
                }
         
            try: 
                print('masuk try')
                if rekomendasi is None or rekomendasi == "":
                    raise ValidationError("Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu")

                with connection.cursor() as cursor:
                    cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                    cursor.execute("SELECT NoSTR FROM DOKTER where username=%s LIMIT 1;", [email])
                    no_str = cursor.fetchone()[0]
                    
                if no_str is None:
                    print("masuk none yg no str")
                    return redirect('dokter:formAppointment')
                print('tes dokter')
                
                print('tes dokter 2')
                #UPDATE TABLE MEMERIKSA 
                with connection.cursor() as cursor:
                    print("masuk update table")
                    cursor.execute("SET search_path to SIRUCO;")
                    cursor.execute(
                    """
                    UPDATE MEMERIKSA SET rekomendasi= '{}'
                    WHERE nik_pasien='{}' AND username_dokter='{}' 
                    AND kode_faskes= '{}' 
                    AND praktek_shift= '{}' AND praktek_tgl='{}';
                    """
                    .format(
                    rekomendasi, 
                    nik, email, 
                    kode,
                    shift, tanggal))

dokter/templates/create-bed-rs.html
{% extends 'base.html' %}

{% block page_content %}
<h1 class="mt-4"> <center> Buat Bed RS </center></h1>

<div class="container d-flex justify-content-center" align="center">

        <form id="formCreate" action="" method="post">
          {% csrf_token %}

          <div class="form-group">

          <div>
          <h4>{{ form.kode_rs.label }}</h4>
          <div class="input-group mb-3 ">   
            {{ form.kode_rs }}
          </div>

          <br>
          <label style="font-size: 23px; font-weight: bold" for="ruanganRS">Kode Ruangan </label>
            <select class="form-control" name="ruanganRS" id="ruanganRS">

            </select>
          <br>

          <br>
          <label style="font-size: 23px; font-weight: bold" for="bedRS">Kode Bed </label>
            <input class="form-control" name="bedRS" id="bedRS" readonly>

            </input>
          <br>


      	    </div>
          <input class="btn btn-outline-primary" type="submit" value="Simpan">

        </form>
   
  </div> 

{% endblock %}
{% block script_content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'dokter:ajaxRuanganBed' %}",
            data: {
                kode_faskes: $('#kode_rs').val()
            },
            async: false,
            success: function (response) {
                response.id.map((e) => {
                    $('#ruanganRS').append(new Option(e, e))
                })
            }
        });

        $('#kode_rs').on('change', function () {
            $('#ruanganRS').find('option').remove()
            $.ajax({
                type: 'GET',
                url: "{% url 'dokter:ajaxRuanganBed' %}",
                data: {
                    kode_faskes: $('#kode_rs').val()
                },
                async: false,
                success: function (response) {
                    response.id.map((e) => {
                        $('#ruanganRS').append(new Option(e, e))
                    })
                }
            });

            $.ajax({
                type: 'GET',
                url: "{% url 'dokter:ajaxKodeBed' %}",
                data: {
                    kode_ruangan: $('#ruanganRS').val()
                },
                async: false,
                success: function (response) {
                    console.log(response)
                    $('#bedRS').val(response.id)
                }
            });
        });

        $.ajax({
            type: 'GET',
            url: "{% url 'dokter:ajaxKodeBed' %}",
            data: {
                kode_ruangan: $('#ruanganRS').val()
            },
            async: false,
            success: function (response) {
                console.log(response)
                $('#bedRS').val(response.id)
            }
        });

        $('#ruanganRS').on('change', function () {
            $('#bedRS').find('value').remove()
            console.log($('#ruanganRS').val())
            $.ajax({
                type: 'GET',
                url: "{% url 'dokter:ajaxKodeBed' %}",
                data: {
                    kode_ruangan: $('#ruanganRS').val()
                },
                async: false,
                success: function (response) {
                    console.log(response)
                    $('#bedRS').val(response.id)
                }
            });
        });
    })
</script>
{% endblock %}

dokter/templates/create-jadwal-dokter.html
{% extends 'base.html' %}

{% block page_content %}

<h1 class="mt-4"> <center> Buat Jadwal Dokter </center></h1>
<br>

{% if message is not None %}
    <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
    {{ message }}
    </div>
    {% endif %}
    <br>
    <br>
    
<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover  justify-content-center" align="center" style="text-align: center;">
		<thead class="thead-dark">
			
				<th>No.</th>
				<th>Kode Faskes</th>
				<th>Shift</th>
                <th>Tanggal</th>
                <th>Buat Jadwal Dokter</th>

		</thead>
		{% for isi in jadwal %}

		<tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ isi.kode_faskes }}</td>
            <td>{{ isi.shift }}</td>
            <td>{{ isi.tanggal | date:'Y-m-d' }}</td>
            <td>
                <form action="{% url 'dokter:createJadwal' %}" method="GET">
                    <input type="hidden" id="kode_faskes" name="kode_faskes" value="{{ isi.kode_faskes }}">
                    <input type="hidden" id="shift" name="shift" value="{{ isi.shift }}">
                    <input type="hidden" id="tanggal" name="tanggal" value="{{ isi.tanggal | date:'Y-m-d' }}">
                    <input type="submit" class="btn btn-success" value="Create">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>		
</div>
{% endblock page_content %}

dokter/templates/create-ruangan-rs.html
{% extends 'base.html' %}

{% block page_content %}

<h1 class="mt-4"> <center> Buat Ruangan RS </center></h1>

  <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'dokter:createRuanganRS' %}" method="POST">
          {% csrf_token %}

          <div class="form-group">
          <div>
            <br>
            <label style="font-size: 23px; font-weight: bold" for="kodeRS">Kode Rumah Sakit</label>
                <select class="form-control" name="kodeRS" id="kodeRS">
                </select>
            <br>

            <br>
            <label style="font-size: 23px; font-weight: bold" for="ruanganRS">Kode Ruangan</label>
                <input class="form-control" name="ruanganRS" id="ruanganRS" readonly>
                </input>
            <br>

            <h5>{{ form.tipe.label }}</h5> 
            <div class="input-group mb-3"> 
                {{ form.tipe }}
            </div>

            </h5>{{ form.harga_ruangan.label }}</h5>
            <div class="input-group mb-3">  
                {{ form.harga_ruangan }}
            </div>

      	</div>
          <input class="btn btn-outline-primary" type="submit" value="Simpan">
        </form>
  </div> 

{% endblock %}
{% block script_content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'dokter:ajaxKodeRS' %}",
            data: {
                kode_faskes: $('#kodeRS').val()
            },
            async: false,
            success: function (response) {
              console.log(response)
                response.id.map((e) => {
                    $('#kodeRS').append(new Option(e, e))
                })
            }
        });

        $('#kodeRS').on('change', function () {
            $('#ruanganRS').find('option').remove()
            console.log($('#ruanganRS').val())
            $.ajax({
                type: 'GET',
                url: "{% url 'dokter:ajaxRuanganRS' %}",
                data: {
                    kode_rs: $('#kodeRS').val()
                },
                async: false,
                success: function (response) {
                    console.log(response)
                    $('#ruanganRS').val(response.id)
                }
            });
        });
    })

</script>
{% endblock %}

dokter/templates/form-appointment.html
{% extends "base.html" %}

{% block page_content %}
<h1> <center> Form Appointment </center></h1>

    {% if message is not None %}
    <div style="padding:auto; width:600px; height:70px; margin:auto; text-align=center;" class="alert alert-danger" role="alert" text-align="center">
    {{ message }}
    </div>
    {% endif %}
    <br>
    <br>

  <div class="container d-flex justify-content-center" align="center">

        <form action="{% url 'dokter:formAppointment' %}" method="post">
          {% csrf_token %}

          <div class="form-group">

          {% comment %} <h4>{{ form.nik.label }}</h4>
            {{ form.nik }} {% endcomment %}

          <label style="font-size: 23px; font-weight: bold" for="nik_pasien">NIK Pasien</label>
            <select class="form-control" name="nik_pasien" id="nik_pasien">
            </select>

          <h4>{{ form.email.label }}</h4>
            {{ form.email }}

          <h4>{{ form.kode_faskes.label }}</h4> 
            {{ form.kode_faskes }}

          <h4>{{ form.tanggal.label }}</h4>
            {{ form.tanggal }}

          <h4>{{ form.shift.label }}</h4>
            {{ form.shift }}

      	    </div>
          <input class="btn btn-outline-primary" type="submit" value="Simpan">

        </form>
   
  </div> 

{% endblock %}
{% block script_content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'dokter:ajaxAppointment' %}",
            data: {
                nik_pasien: $('#nik_pasien').val()
            },
            async: false,
            success: function (response) {
              console.log(response)
                response.id.map((e) => {
                    $('#nik_pasien').append(new Option(e, e))
                })
            }
        });
    })
</script>
{% endblock %}

dokter/templates/list-appointment.html
{% extends 'base.html' %}

{% block page_content %}

<h1 class="mt-4"> <center> List Appoinment </center></h1>
<br>

<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover  justify-content-center" align="center" style="text-align: center;">
		<thead class="thead-dark">
			
				<th>No.</th>
				<th>NIK Pasien</th>
				<th>Email Dokter</th>
				<th>Faskes</th>
				<th>Shift</th>
                <th>Tanggal</th>
                <th>Rekomendasi</th>
                {% if request.session.role == 'ADMIN_SATGAS' or request.session.role == 'DOKTER' %}
				<th>Action</th>
				{% endif %}

		</thead>
		{% for isi in appointment %}

		<tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ isi.nik_pasien }}</td>
            <td>{{ isi.username_dokter }}</td>
            <td>{{ isi.kode_faskes }}</td>
            <td>{{ isi.praktek_shift }}</td>
            <td>{{ isi.praktek_tgl | date:'d-m-Y' }}</td>
            <td>{{ isi.rekomendasi }}</td>
            
            {% if request.session.role == 'ADMIN_SATGAS' %}
            <td>
                <form action="{% url 'dokter:deleteAppointment' %}" method="GET">
                   <input type="hidden" id="nik" name="nik" value="{{ isi.nik_pasien }}">
                    <input type="hidden" id="username" name="username" value="{{ isi.username_dokter }}">
                    <input type="hidden" id="kode_faskes" name="kode_faskes" value="{{ isi.kode_faskes }}">
                    <input type="hidden" id="shift" name="shift" value="{{ isi.praktek_shift }}">
                    <input type="hidden" id="tanggal" name="tanggal" value="{{ isi.praktek_tgl | date:'Y-m-d' }}">
                    <input type="submit" class="btn btn-success" value="Delete">
                </form>
            </td>
            {% endif %}
            {% if request.session.role == 'DOKTER' %}
            <td>
                <form action="{% url 'dokter:updateAppointment' %}" method="GET">
                    <input type="hidden" id="nik" name="nik" value="{{ isi.nik_pasien }}">
                    <input type="hidden" id="username" name="username" value="{{ isi.username_dokter }}">
                    <input type="hidden" id="kode_faskes" name="kode_faskes" value="{{ isi.kode_faskes }}">
                    <input type="hidden" id="shift" name="shift" value="{{ isi.praktek_shift }}">
                    <input type="hidden" id="tanggal" name="tanggal" value="{{ isi.praktek_tgl | date:'Y-m-d' }}">
                    <input type="submit" class="btn btn-success" value="Update">
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>		
</div>

    <div class="col text-center" style="margin: 20px 20px">
        <form action="{% url 'dokter:createAppointment' %}" method="GET">
            <input type="submit" class="btn btn-outline-primary" value="SIMPAN">
        </form>
    </div>
{% endblock page_content %}

dokter/templates/list-bed-rs.html
{% extends 'base.html' %}

{% block page_content %}
<h1 class="mt-4"> <center> List Bed RS </center></h1>
<div class="container d-flex justify-content-center" align="center">
			
	<table class="table table-hover" align="center">
		<thead class="thead-dark">
			
				<th>No.</th>
				<th>Kode RS</th>
				<th>Kode Ruangan</th>
				<th>Kode Bed</th>
				<th>Action</th>

		</thead>
		{% for isi in data %}
        {% comment %} {% for isi2 in data2 %} {% endcomment %}
		<tr>
            <td>{{ isi.nomor }}</td>
            <td>{{ isi.koders }}</td>
            <td>{{ isi.koderuangan }}</td>
            <td>{{ isi.kodebed }}</td>

            {% if isi.kodebed not in outkodebed %}
            <td>
                <form action="{% url 'dokter:deleteBedRS'%}" method="GET">
                    <input type="hidden" id="koders" name="koders" value="{{ isi.koders }}">
                    <input type="hidden" id="koderuangan" name="koderuangan" value="{{ isi.koderuangan }}">
                    <input type="hidden" id="kodebed" name="kodebed" value="{{ isi.kodebed }}">
                    <input type="submit" class="btn btn-success" value="Delete">
                </form>
            </td>
            {% endif %}

        </tr>
        {% endfor %}
        {% comment %} {% endfor %} {% endcomment %}
    </table>		
</div>
{% endblock page_content %}